self attention mechanism is also called *scaled dot-product attention*

*computing attention weights step by step*

In [1]:

import torch
inputs = torch.tensor([
    [0.43, 0.15, 0.89],  # your        (x^1)
    [0.55, 0.87, 0.66],  # journey     (x^2)
    [0.57, 0.85, 0.64],  # starts     (x^3)
    [0.22, 0.58, 0.33],  # with       (x^4)
    [0.77, 0.25, 0.10],  # one        (x^5)
    [0.05, 0.80, 0.55]  # step        (X^6)
])


In [2]:
print(inputs)

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])


In [4]:
print(inputs.shape)

torch.Size([6, 3])


In [5]:
x_2 = inputs[1]  # [0.5500, 0.8700, 0.6600]
d_in=inputs.shape[1] # input embedding size (3)
d_out=2  # output embedding size

In [6]:
# initializing 3 weights matrices (weight parameters)

torch.manual_seed(123)
W_query=torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key=torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value=torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)

# required_grad = True duing model training must


In [7]:
print(W_query)

Parameter containing:
tensor([[0.2961, 0.5166],
        [0.2517, 0.6886],
        [0.0740, 0.8665]])


In [8]:
query_2=x_2@W_query # query vector for token 2
key_2=x_2@W_key # key vector for token 2
value_2=x_2@W_value # valuevector for token 2



In [9]:
print(query_2)
print(key_2)
print(value_2)

tensor([0.4306, 1.4551])
tensor([0.4433, 1.1419])
tensor([0.3951, 1.0037])


In [10]:
# even though for finding context vector for query 2
# we need to find key, value vectors for all input elements as they
# involved in computing attention weights with respect to query 2


keys=inputs@W_key
values=inputs@W_value


In [11]:
print(keys)
print(keys.shape)

tensor([[0.3669, 0.7646],
        [0.4433, 1.1419],
        [0.4361, 1.1156],
        [0.2408, 0.6706],
        [0.1827, 0.3292],
        [0.3275, 0.9642]])
torch.Size([6, 2])


In [12]:
print(values)
print(values.shape)

tensor([[0.1855, 0.8812],
        [0.3951, 1.0037],
        [0.3879, 0.9831],
        [0.2393, 0.5493],
        [0.1492, 0.3346],
        [0.3221, 0.7863]])
torch.Size([6, 2])


*computing attention scores*

In [13]:
# to fidning attn socre = dot prodcut of query and keys

# we've taken for query 2
# attention score wrt query 1
keys_1=keys[0]
attn_score_21=query_2.dot(keys_1)
print(attn_score_21)



tensor(1.2705)


In [14]:
# attn score wrt query 2
keys_2=keys[1]
attn_score_22=query_2.dot(keys_2)
print(attn_score_22)

tensor(1.8524)


In [15]:
# attention score for given inputs wrt query 2
attn_scores_2 = query_2@keys.T
print(attn_scores_2)


tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440])


In [16]:
print(keys.shape)

torch.Size([6, 2])


*computing attention weights*

In [17]:
d_k=keys.shape[-1] # embedding dimension of keys

# attention score scaled: dividing them by sqrt of d_k
attn_weights_2=torch.softmax(attn_scores_2/d_k**0.5, dim=-1)
print(attn_weights_2)


tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820])


*context vector*

In [18]:
context_vec_2=attn_weights_2@values
print(context_vec_2)


tensor([0.3061, 0.8210])
